#spring:
#  data:
#    mongodb:
#      database: airportal
#      host:
#      port:
#      username:
#      password:
#      authentication-database: admin
#  mail:
#    host:
#    username:
#    password:
#    default-encoding: UTF-8
#    enable: false
#
#minio:
#  endpoint:
#  accessKey:
#  secretKey:
#  bucketName:
#  downloadUri:
#  path:
#
#swagger:
#  enable: false
#
#airportal:
#  register:
#    enable: false

